=== mromanello/DTS-validator/schemas/entry_response.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "entry_response_schema.json",
    "$comment": "https://distributed-text-services.github.io/specifications/versions/1-alpha/#entry-endpoint",
    "type": "object",
    "properties": {
        "@context": {"type": "string"},
        "@id": {"type": "string"},
        "@type": {"type": "string"},
        "dtsVersion": {
            "type": "string",
            "enum": ["1-alpha", "unstable"]
        },
        "collection": {"type": "string"},
        "document": {"type": "string"},
        "navigation": {"type": "string"}
    },
    "required": [
        "@context", "@id", "@type", "dtsVersion", "collection", "document", "navigation"
    ]
}

=== mromanello/DTS-validator/tests/data/entry/entry_docs_response.json
{
  "@context": "https://distributed-text-services.github.io/specifications/context/1-alpha1.json",
  "dtsVersion": "1-alpha",
  "@id": "/api/dts/",
  "@type": "EntryPoint",
  "collection": "/api/dts/collection/{?id,page,nav}",
  "navigation" : "/api/dts/navigation/{?resource,ref,start,end,down,tree,page}",
  "document": "/api/dts/document/{?resource,ref,start,end,tree,mediaType}"
}
